"""I miei giudizi a mano sul campione d'esame v1 (280 casi difficili, con testo),
secondo docs/rubrica-classificazione.md. Famiglia sempre; seniority,
contratto e remoto SOLO dove il testo li dice chiaramente (None = non
giudicato, non entra nel punteggio di quella testa).

Produce campione_esame_v1_giudicato.json e stampa l'accordo di ogni maestro
(dizionario, GLM) col giudizio a mano: e' la misura di quanto vale
ciascuno sui casi difficili."""
import json
from collections import Counter, defaultdict

# idx: (famiglia, seniority, employment_type, remote)
G = {
 0: ("Finance & Accounting", "senior", None, None),
 1: ("Retail", "junior", "temporary", None),
 2: ("Manufacturing", None, "temporary", None),
 3: ("Retail", None, "part_time", None),
 4: ("Trades", "mid", "temporary", None),
 5: ("Engineering", None, None, None),
 6: ("Customer Service & Support", "junior", "part_time", None),
 7: ("Software", "senior", None, "onsite"),
 8: ("Sales", None, None, None),
 9: ("Construction", "lead", None, None),
 10: ("Trades", "junior", "full_time", "onsite"),
 11: ("Technology", "senior", None, None),
 12: ("Human Resources", "mid", None, "onsite"),
 13: ("Manufacturing", "junior", "full_time", "onsite"),
 14: ("Transportation", None, "full_time", None),
 15: ("Finance & Accounting", None, None, "remote"),
 16: ("Technology", "lead", "full_time", None),
 17: ("unknown", None, None, None),
 18: ("Manufacturing", "junior", "full_time", "onsite"),
 19: ("Education", "mid", None, "onsite"),
 20: ("Education", None, "contract", None),
 21: ("Administrative", None, "temporary", "onsite"),
 22: ("Food & Beverage", None, "part_time", "onsite"),
 23: ("Food & Beverage", "junior", None, "onsite"),
 24: ("Consulting", "senior", None, None),
 25: ("Logistics", None, None, None),
 26: ("Retail", None, "temporary", None),
 27: ("Retail", None, None, None),
 28: ("Healthcare", "mid", "contract", "onsite"),
 29: ("Administrative", None, "full_time", None),
 30: ("Retail", "lead", "part_time", None),
 31: ("Trades", None, None, None),
 32: ("Logistics", None, "full_time", None),
 33: ("Administrative", "junior", None, "hybrid"),
 34: ("Logistics", None, "temporary", None),
 35: ("Administrative", None, "full_time", None),
 36: ("Administrative", "intern", "internship", None),
 37: ("Finance & Accounting", None, None, "remote"),
 38: ("unknown", None, None, None),
 39: ("Transportation", "senior", "full_time", None),
 40: ("Food & Beverage", None, None, None),
 41: ("Social Services", None, None, None),
 42: ("Technology", None, None, "onsite"),
 43: ("Finance & Accounting", "senior", None, "onsite"),
 44: ("Administrative", "junior", "full_time", None),
 45: ("Administrative", None, None, None),
 46: ("Sports & Recreation", None, None, "onsite"),
 47: ("Legal", "senior", None, None),
 48: ("Finance & Accounting", "junior", None, None),
 49: ("Trades", None, None, None),
 50: ("Hospitality", "junior", "full_time", "onsite"),
 51: ("Transportation", "intern", "apprenticeship", None),
 52: ("Education", "junior", "temporary", "onsite"),
 53: ("Transportation", None, "full_time", None),
 54: ("Trades", None, None, "onsite"),
 55: ("Software", None, "full_time", None),
 56: ("Education", None, "contract", "remote"),
 57: ("Management & Leadership", "head", None, None),
 58: ("Education", None, "contract", None),
 59: ("Education", None, None, "onsite"),
 60: ("Sports & Recreation", None, None, "onsite"),
 61: ("Manufacturing", None, None, None),
 62: ("Sales", "head", None, None),
 63: ("Retail", None, "full_time", None),
 64: ("Software", "senior", None, "remote"),
 65: ("Finance & Accounting", "head", None, None),
 66: ("Trades", None, None, None),
 67: ("Healthcare", None, None, "onsite"),
 68: ("Retail", None, "full_time", None),
 69: ("Healthcare", None, "temporary", "onsite"),
 70: ("Administrative", None, "temporary", None),
 71: ("Construction", "junior", None, None),
 72: ("Trades", "mid", None, "onsite"),
 73: ("Trades", None, None, "onsite"),
 74: ("Customer Service & Support", None, "full_time", None),
 75: ("Trades", None, None, "onsite"),
 76: ("Retail", "lead", "full_time", None),
 77: ("Education", "junior", "part_time", "onsite"),
 78: ("Transportation", None, "full_time", None),
 79: ("Manufacturing", None, None, None),
 80: ("Food & Beverage", "mid", None, None),
 81: ("Food & Beverage", "junior", None, "onsite"),
 82: ("Sports & Recreation", None, "part_time", None),
 83: ("Technology", "mid", "full_time", "onsite"),
 84: ("Trades", None, None, "onsite"),
 85: ("Software", "senior", None, None),
 86: ("Manufacturing", "junior", None, None),
 87: ("Administrative", None, "part_time", None),
 88: ("Trades", "mid", "full_time", "onsite"),
 89: ("Administrative", "junior", "full_time", "hybrid"),
 90: ("Trades", None, None, None),
 91: ("Food & Beverage", "lead", None, None),
 92: ("Marketing", "junior", "full_time", None),
 93: ("Finance & Accounting", "junior", None, "onsite"),
 94: ("Manufacturing", "intern", "internship", None),
 95: ("Social Services", "junior", "full_time", "onsite"),
 96: ("Sales", "junior", None, None),
 97: ("Technology", "intern", "part_time", None),
 98: ("Sales", "mid", None, "hybrid"),
 99: ("Data & Analytics", None, None, "remote"),
 100: ("Management & Leadership", "intern", "full_time", None),
 101: ("Administrative", None, "contract", "remote"),
 102: ("Finance & Accounting", "head", None, "remote"),
 103: ("Trades", None, None, None),
 104: ("unknown", None, None, None),
 105: ("Food & Beverage", None, "part_time", "onsite"),
 106: ("Sales", "senior", None, None),
 107: ("Data & Analytics", None, None, None),
 108: ("Finance & Accounting", None, None, None),
 109: ("Customer Service & Support", None, "full_time", "onsite"),
 110: ("Technology", "senior", None, None),
 111: ("unknown", None, None, None),
 112: ("Retail", "intern", "internship", "onsite"),
 113: ("Administrative", None, None, None),
 114: ("Technology", "senior", None, None),
 115: ("Sales", None, None, "hybrid"),
 116: ("Finance & Accounting", "head", "contract", None),
 117: ("Sales", "intern", "part_time", None),
 118: ("Sports & Recreation", "mid", None, "onsite"),
 119: ("Engineering", "senior", None, None),
 120: ("Customer Service & Support", None, None, None),
 121: ("Software", None, None, None),
 122: ("Technology", None, None, "remote"),
 123: ("Finance & Accounting", None, None, None),
 124: ("Customer Service & Support", None, "full_time", None),
 125: ("Sports & Recreation", "lead", None, None),
 126: ("Trades", None, "full_time", None),
 127: ("Logistics", "senior", "full_time", "onsite"),
 128: ("Logistics", None, None, None),
 129: ("Logistics", None, "part_time", None),
 130: ("Retail", None, None, None),
 131: ("Construction", "junior", None, "onsite"),
 132: ("Education", "mid", None, "onsite"),
 133: ("Finance & Accounting", "junior", None, None),
 134: ("Food & Beverage", None, None, "onsite"),
 135: ("Food & Beverage", "junior", "temporary", None),
 136: ("Hospitality", "junior", "part_time", "onsite"),
 137: ("Software", "junior", "contract", "onsite"),
 138: ("Hospitality", "mid", None, "onsite"),
 139: ("Social Services", None, None, None),
 140: ("Software", "senior", None, "remote"),
 141: ("Administrative", None, "temporary", None),
 142: ("Administrative", None, "part_time", None),
 143: ("Technology", "junior", None, "onsite"),
 144: ("Education", None, None, None),
 145: ("Retail", "lead", "full_time", None),
 146: ("Sales", "lead", None, None),
 147: ("Food & Beverage", "lead", None, None),
 148: ("Food & Beverage", "mid", None, None),
 149: ("Technology", "junior", None, None),
 150: ("Retail", None, None, None),
 151: ("Engineering", "senior", None, None),
 152: ("Sales", None, "contract", None),
 153: ("Administrative", "junior", "part_time", "onsite"),
 154: ("Trades", "senior", "full_time", "onsite"),
 155: ("Healthcare", None, None, "onsite"),
 156: ("Technology", "lead", None, None),
 157: ("Sales", None, None, None),
 158: ("Manufacturing", "intern", "apprenticeship", None),
 159: ("Transportation", None, "part_time", "onsite"),
 160: ("Construction", None, None, None),
 161: ("Food & Beverage", "mid", None, None),
 162: ("Hospitality", None, None, None),
 163: ("Sales", None, None, "hybrid"),
 164: ("Sales", None, None, None),
 165: ("Sports & Recreation", None, None, None),
 166: ("Healthcare", "junior", "part_time", "onsite"),
 167: ("Software", "mid", None, None),
 168: ("Customer Service & Support", None, "full_time", None),
 169: ("Administrative", None, "full_time", None),
 170: ("Healthcare", None, None, None),
 171: ("Transportation", None, "full_time", None),
 172: ("Finance & Accounting", "mid", "full_time", None),
 173: ("Construction", "mid", "full_time", "onsite"),
 174: ("Trades", None, None, None),
 175: ("Customer Service & Support", None, "temporary", None),
 176: ("Administrative", "junior", None, "onsite"),
 177: ("Retail", "junior", None, "onsite"),
 178: ("Software", "senior", None, "hybrid"),
 179: ("Food & Beverage", "lead", None, "onsite"),
 180: ("Logistics", None, "temporary", None),
 181: ("Education", "mid", "contract", "onsite"),
 182: ("Customer Service & Support", "junior", None, None),
 183: ("unknown", None, None, None),
 184: ("Engineering", "mid", None, "onsite"),
 185: ("Healthcare", "junior", None, "onsite"),
 186: ("Sales", None, None, None),
 187: ("Trades", "mid", None, "onsite"),
 188: ("Education", "junior", "full_time", "onsite"),
 189: ("Transportation", None, None, None),
 190: ("Retail", "junior", "temporary", None),
 191: ("Sports & Recreation", None, None, None),
 192: ("Sales", "mid", None, None),
 193: ("Engineering", None, None, None),
 194: ("Logistics", None, "temporary", None),
 195: ("Technology", None, None, None),
 196: ("Trades", None, None, None),
 197: ("Technology", "lead", None, None),
 198: ("Consulting", "lead", "contract", "hybrid"),
 199: ("Food & Beverage", "junior", None, "onsite"),
 200: ("Education", None, None, "onsite"),
 201: ("Food & Beverage", None, None, None),
 202: ("Retail", None, "temporary", None),
 203: ("Administrative", None, "temporary", None),
 204: ("Logistics", None, None, None),
 205: ("Software", "senior", None, None),
 206: ("Trades", None, None, None),
 207: ("Finance & Accounting", None, "full_time", None),
 208: ("Sports & Recreation", None, None, None),
 209: ("Creative & Media", "head", None, None),
 210: ("Engineering", "senior", None, None),
 211: ("Manufacturing", "mid", "full_time", "onsite"),
 212: ("Administrative", None, None, "onsite"),
 213: ("Consulting", "mid", None, None),
 214: ("Food & Beverage", None, "part_time", None),
 215: ("Transportation", None, "full_time", None),
 216: ("Software", "mid", None, "remote"),
 217: ("Construction", None, None, None),
 218: ("Technology", None, None, None),
 219: ("Education", "junior", None, "onsite"),
 220: ("Healthcare", "mid", "temporary", "onsite"),
 221: ("Logistics", None, None, None),
 222: ("Software", None, None, None),
 223: ("Marketing", "mid", "full_time", "remote"),
 224: ("Sales", None, None, "onsite"),
 225: ("Technology", "senior", None, None),
 226: ("Construction", "mid", None, "onsite"),
 227: ("Software", "senior", None, "remote"),
 228: ("Retail", "junior", "full_time", None),
 229: ("Administrative", "intern", None, None),
 230: ("Software", "senior", None, None),
 231: ("Healthcare", None, "full_time", None),
 232: ("Food & Beverage", None, "part_time", None),
 233: ("Healthcare", None, None, None),
 234: ("Marketing", "lead", None, "remote"),
 235: ("Engineering", "mid", None, "onsite"),
 236: ("Manufacturing", None, "full_time", None),
 237: ("Construction", "lead", None, None),
 238: ("Manufacturing", "junior", None, None),
 239: ("Science & Research", "mid", None, "remote"),
 240: ("Transportation", "lead", None, None),
 241: ("Software", "senior", None, "remote"),
 242: ("Sales", None, "full_time", None),
 243: ("Software", None, None, "remote"),
 244: ("Manufacturing", None, "temporary", None),
 245: ("Manufacturing", "junior", "temporary", "onsite"),
 246: ("Retail", None, None, "onsite"),
 247: ("Food & Beverage", "lead", "full_time", "onsite"),
 248: ("Consulting", "senior", None, None),
 249: ("Retail", "junior", "part_time", None),
 250: ("Customer Service & Support", None, None, None),
 251: ("Software", None, None, "remote"),
 252: ("Trades", "mid", "full_time", "onsite"),
 253: ("Finance & Accounting", "senior", "full_time", "onsite"),
 254: ("Software", None, None, None),
 255: ("Construction", None, None, None),
 256: ("unknown", None, None, None),
 257: ("Retail", None, "part_time", "onsite"),
 258: ("Transportation", None, "full_time", None),
 259: ("Finance & Accounting", "junior", None, None),
 260: ("Retail", None, None, None),
 261: ("Customer Service & Support", None, None, None),
 262: ("Sales", None, None, "onsite"),
 263: ("Transportation", None, None, None),
 264: ("Retail", None, "part_time", None),
 265: ("Customer Service & Support", None, "full_time", "remote"),
 266: ("Social Services", None, None, "onsite"),
 267: ("Sales", None, None, None),
 268: ("Administrative", None, None, None),
 269: ("Healthcare", None, "part_time", None),
 270: ("Creative & Media", "lead", "contract", None),
 271: ("unknown", None, None, None),
 272: ("Management & Leadership", "junior", None, None),
 273: ("Retail", None, "part_time", None),
 274: ("Healthcare", "junior", "part_time", "onsite"),
 275: ("Retail", "junior", "part_time", None),
 276: ("Construction", "mid", "full_time", "onsite"),
 277: ("Sports & Recreation", None, None, "onsite"),
 278: ("Technology", "senior", "full_time", None),
 279: ("Technology", "senior", None, "hybrid"),
}

BASE = "/private/tmp/claude-501/-Users-giusepperanno-Desktop-nivult-engine/df0109ef-d46d-45d4-b08b-f8d74060d94f/scratchpad"
righe = json.load(open(f"{BASE}/campione_esame_v1.json"))
assert len(righe) == len(G) == 280, (len(righe), len(G))
out = []
acc = defaultdict(lambda: [0, 0])          # maestro -> [accordi, totale]
teste = {"seniority": [0, 0], "employment_type": [0, 0], "remote": [0, 0]}
disaccordi = []
for i, r in enumerate(righe):
    fam, sen, et, rem = G[i]
    maestro = "glm" if r["model"].startswith("glm") else "dizionario"
    if fam != "unknown":
        acc[maestro][1] += 1
        if r["family_label"] == fam:
            acc[maestro][0] += 1
        else:
            disaccordi.append((i, maestro, r["family_label"], fam, r["title"][:60]))
    for testa, mio in (("seniority", sen), ("employment_type", et), ("remote", rem)):
        if mio is not None and r.get(testa) is not None:
            teste[testa][1] += 1
            teste[testa][0] += r[testa] == mio
    out.append({"id": r["id"], "title": r["title"], "location": r["location"], "text": r["text"],
                "family": fam, "seniority": sen, "employment_type": et, "remote": rem,
                "family_prev": r["family_label"], "model_prev": r["model"]})
json.dump(out, open(f"{BASE}/campione_esame_v1_giudicato.json", "w"), ensure_ascii=False, indent=0)
print("giudicati:", len(out), "| unknown:", sum(1 for x in out if x["family"] == "unknown"))
for m, (a, t) in acc.items():
    print(f"accordo famiglia {m:11s}: {a}/{t} = {100*a/t:.1f}%")
for testa, (a, t) in teste.items():
    print(f"accordo {testa:16s} (dove entrambi giudicano): {a}/{t} = {100*a/t if t else 0:.1f}%")
print("\nfamiglie piu' confuse (etichetta esistente -> mia):")
for (da, a), n in Counter((d[2], d[3]) for d in disaccordi).most_common(15):
    print(f"  {n:2d}  {da} -> {a}")
print("\ndisaccordi GLM:")
for d in disaccordi:
    if d[1] == "glm":
        print("  #%d %s -> %s | %s" % (d[0], d[2], d[3], d[4]))
